"""Type stubs for sqlite_license_feature_repository.

This file provides type hints while maintaining clean architecture boundaries.
"""

from __future__ import annotations

from pathlib import Path

from license_management.application.license_file_parser import ParsedLicenseFeature
from license_management.domain.models.license_record import LicenseRecord

class SqliteLicenseFeatureRepository:
    def __init__(self, db_path: Path) -> None: ...
    @property
    def current_workspace(self) -> str: ...
    def switch_workspace(self, workspace: str) -> None: ...
    def enter_staging_workspace(self) -> None: ...
    def publish_staging_to_committed(self) -> int: ...
    def replace_for_record(
        self, record: LicenseRecord, features: list[ParsedLicenseFeature]
    ) -> None: ...
    def delete_for_record(self, record: LicenseRecord) -> None: ...
    def list_for_record(self, record: LicenseRecord) -> list[tuple[str, str, int]]: ...
