from __future__ import annotations

from typing import Protocol

from license_management.domain.models.license_record import LicenseRecord


class LicenseRepository(Protocol):
    """Repository contract for license records."""

    @property
    def current_workspace(self) -> str: ...

    def upsert(self, record: LicenseRecord) -> None: ...

    def get(self, record_id: str) -> LicenseRecord | None: ...

    def list_all(self) -> list[LicenseRecord]: ...

    def delete(self, record_id: str) -> bool: ...

    def switch_workspace(self, workspace: str) -> None: ...

    def enter_staging_workspace(self) -> None: ...

    def publish_staging_to_committed(self) -> int: ...
